var x5CartData = {
	// General Cart Settings
	'settings': {
		'indexpage': 'cart/index.html',
		'continue_shopping_page': 'https://naturefreshlanka.com/index.html',
		'vat': 0.2,
		'vattype': 'included', // included|excluded|none
		'currency': '$',
		'currency_id': 'USD',
		'showShipmentFields': false,
		'cartCookie': 'x5CartProductsj90t0wncjqi39d1w',
		'formCookie': 'x5CartFormj90t0wncjqi39d1w',
		'currency_format': '####.@@ [C]',
		'currency_format_zeroas': '0',
		'order_no_format': '[yy][mm][dd]-[A-Z][A-Z][0-9][0-9]',
		'formAutocomplete': true,
		'formValidation': 'tip',
		'remove_from_cart_icon': 'cart/images/cart-remove.png',
		'add_to_cart_icon': 'cart/images/cart-add.png',
		'minimumAmount': 0,
		'currencies': [{ "value": "ALL", "text": "Albania, Leke, Lek" }, { "value": "USD", "text": "United States of America, Dollars, $" }, { "value": "AFN", "text": "Afghanistan, Afghanis, ؋" }, { "value": "ARS", "text": "Argentina, Pesos, $" }, { "value": "AUD", "text": "Australia, Dollars, $" }, { "value": "BGN", "text": "Bulgarian, Lev, лв" }, { "value": "BRL", "text": "Brazil, Reais, R$" }, { "value": "GBP", "text": "United Kingdom, Pounds, £" }, { "value": "BND", "text": "Brunei Darussalam, Dollars, $" }, { "value": "CAD", "text": "Canada, Dollars, $" }, { "value": "CNY", "text": "China, Yuan Renminbi, ¥" }, { "value": "HRK", "text": "Croatia, Kuna, ₡" }, { "value": "CZK", "text": "Czech Republic, Koruny, Kč" }, { "value": "DKK", "text": "Denmark, Kroner, kr" }, { "value": "EGP", "text": "Egypt, Pounds, £" }, { "value": "EUR", "text": "Euro, €" }, { "value": "GTQ", "text": "Guatemala, Quetzales, Q" }, { "value": "HKD", "text": "Hong Kong, Dollars, $" }, { "value": "HUF", "text": "Hungary, Forint, Ft" }, { "value": "ISK", "text": "Iceland, Kronur, kr" }, { "value": "INR", "text": "India, Rupees, Rs" }, { "value": "IDR", "text": "Indonesia, Rupiahs, Rp" }, { "value": "IRR", "text": "Iran, Rials, ﷼" }, { "value": "ILS", "text": "Israel, New Shekels, ₪" }, { "value": "JPY", "text": "Japan, Yen, ¥" }, { "value": "KZT", "text": "Kazakhstan, Tenge, тг" }, { "value": "KPW", "text": "Korea (North), Won, ₩" }, { "value": "KRW", "text": "Korea (South), Won, ₩" }, { "value": "LVL", "text": "Latvia, Lati, Ls" }, { "value": "LTL", "text": "Lithuania, Litai, Lt" }, { "value": "MYR", "text": "Malaysia, Ringgits, RM" }, { "value": "MXN", "text": "Mexico, Pesos, $" }, { "value": "NZD", "text": "New Zealand, Dollars, $" }, { "value": "NOK", "text": "Norway, Kroner, kr" }, { "value": "OMR", "text": "Oman, Rials, ﷼" }, { "value": "PLN", "text": "Poland, Zlotych, zł" }, { "value": "QAR", "text": "Qatar, Rials, ﷼" }, { "value": "RON", "text": "Romania, New Lei, lei" }, { "value": "RUB", "text": "Russia, Rubles, руб" }, { "value": "SAR", "text": "Saudi Arabia, Riyals, ﷼" }, { "value": "RSD", "text": "Serbia, Dinars, Дин." }, { "value": "SGD", "text": "Singapore, Dollars, $" }, { "value": "ZAR", "text": "South Africa, Rand, R" }, { "value": "SEK", "text": "Sweden, Kronor, kr" }, { "value": "CHF", "text": "Switzerland, Francs, CHF" }, { "value": "TWD", "text": "Taiwan, New Dollars, NT$" }, { "value": "THB", "text": "Thailand, Baht, ฿" }, { "value": "TTD", "text": "Trinidad and Tobago, Dollars, TT$" }, { "value": "TRY", "text": "Turkey, Lira, ₺" }, { "value": "UAH", "text": "Ukraine, Hryvnia, ₴" }]
	},

	// Cart Products
	'products': {
		'jbaz9uxp': {
			'id': 'jbaz9uxp',
			'id_user': 'AVOCADO',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'AVOCADO',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/1-AVOCADO.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'0kd6d4cg': {
			'id': '0kd6d4cg',
			'id_user': 'BANANA',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'BANANA',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/2-BANANA.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'5sg16vet': {
			'id': '5sg16vet',
			'id_user': 'BELI',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'BELI',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/3-BELI.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'45stwwdx': {
			'id': '45stwwdx',
			'id_user': 'CANTELOUPE MELON',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'CANTELOUPE MELON',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/4-CANTELOUPE-MELON.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'mjli3ige': {
			'id': 'mjli3ige',
			'id_user': 'CHERIMOYA',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'CHERIMOYA',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/5-CHERIMOYA.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'bk0o66xa': {
			'id': 'bk0o66xa',
			'id_user': 'DRAGON FRUIT',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'DRAGON FRUIT',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/6-DRAGON-FRUIT.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'85cncytn': {
			'id': '85cncytn',
			'id_user': 'GUAVA',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'GUAVA',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/7-GUAVA.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'rmfxd11l': {
			'id': 'rmfxd11l',
			'id_user': 'HONEYDEW MELON',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'HONEYDEW MELON',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/8-HONEYDEW-MELON.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'd5uxh8ti': {
			'id': 'd5uxh8ti',
			'id_user': 'LEMON',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'LEMON',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/9-LEMON.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'3f6t4lva': {
			'id': '3f6t4lva',
			'id_user': 'MANGOSTEEN',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'MANGOSTEEN',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/10-MANGOSTEEN.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'no6jjrhh': {
			'id': 'no6jjrhh',
			'id_user': 'MANGO',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'MANGO',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/11-MANGO.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'e9c3mv4u': {
			'id': 'e9c3mv4u',
			'id_user': 'NARANG',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'NARANG',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/12-NARANG.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'mo0hsjj2': {
			'id': 'mo0hsjj2',
			'id_user': 'NELLI',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'NELLI',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/13-NELLI.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'dhlbj5q1': {
			'id': 'dhlbj5q1',
			'id_user': 'PAPAYA',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'PAPAYA',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/14-PAPAYA.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'1tl8brax': {
			'id': '1tl8brax',
			'id_user': 'PASSION FRUIT',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'PASSION FRUIT',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/15-PASSION-FRUIT.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'ltdt8x9v': {
			'id': 'ltdt8x9v',
			'id_user': 'PEARS',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'PEARS',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/16-PEARS.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'v8hcxz7v': {
			'id': 'v8hcxz7v',
			'id_user': 'PINEAPPALE',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'PINEAPPALE',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/17-PINEAPPALE.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'ybezoo3h': {
			'id': 'ybezoo3h',
			'id_user': 'RAMBUTTAN',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'RAMBUTTAN',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/18-RAMBUTTAN.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'hvz3yfmz': {
			'id': 'hvz3yfmz',
			'id_user': 'SWEET CORN',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'SWEET CORN',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/19-SWEET-CORN.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'2r2izedj': {
			'id': '2r2izedj',
			'id_user': 'SOUR SUP',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'SOUR SUP',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/20-SOUR-SUP.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'77408aej': {
			'id': '77408aej',
			'id_user': 'STRAWBERRY',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'STRAWBERRY',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/21-STRAWBERRY.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'nxvxeq08': {
			'id': 'nxvxeq08',
			'id_user': 'WOOD APPLE',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'WOOD APPLE',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/22-WOOD-APPLE.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'iw3fvbey': {
			'id': 'iw3fvbey',
			'id_user': 'WATER MELON',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'WATER MELON',
			'category': '7hbgts3k',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/23-WATER-MELON.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'74ob23xu': {
			'id': '74ob23xu',
			'id_user': 'BLACK PEPPER',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'BLACK PEPPER',
			'category': 'mnplp9ju',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/1-BLACK-PEPPER.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'3trzb3j5': {
			'id': '3trzb3j5',
			'id_user': 'CLOVE',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'CLOVE',
			'category': 'mnplp9ju',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/2-CLOVE.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'7hbx7klk': {
			'id': '7hbx7klk',
			'id_user': 'CINNAMON QUILLS',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'CINNAMON QUILLS',
			'category': 'mnplp9ju',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/3-CINNAMON-QUILLS.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'jv7tzk0f': {
			'id': 'jv7tzk0f',
			'id_user': 'CINNAMON CHIPS',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'CINNAMON CHIPS',
			'category': 'mnplp9ju',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/4-CINNAMON-CHIPS.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'249y6nev': {
			'id': '249y6nev',
			'id_user': 'CARDAMOM',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'CARDAMOM',
			'category': 'mnplp9ju',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/5-CARDAMOM.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'tc7rpc39': {
			'id': 'tc7rpc39',
			'id_user': 'GINGER',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'GINGER',
			'category': 'mnplp9ju',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/6-GINGER.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'5fsvlynd': {
			'id': '5fsvlynd',
			'id_user': 'LEMON GRASS',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'LEMON GRASS',
			'category': 'mnplp9ju',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/7-LEMON-GRASS.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'm03sdsek': {
			'id': 'm03sdsek',
			'id_user': 'MACE',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'MACE',
			'category': 'mnplp9ju',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/8-MACE.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'0i4jjzpx': {
			'id': '0i4jjzpx',
			'id_user': 'NUTMEG',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'NUTMEG',
			'category': 'mnplp9ju',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/9-NUTMEG.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'8mv1wg40': {
			'id': '8mv1wg40',
			'id_user': 'TURMERIC',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'TURMERIC',
			'category': 'mnplp9ju',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/10-TURMERIC.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'x0ctnf6x': {
			'id': 'x0ctnf6x',
			'id_user': 'VANILLA',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'VANILLA',
			'category': 'mnplp9ju',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/11-VANILLA.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'ydku083o': {
			'id': 'ydku083o',
			'id_user': 'WHITE PEPPER',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'WHITE PEPPER',
			'category': 'mnplp9ju',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/12-WHITE-PEPPER.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'muqtvpec': {
			'id': 'muqtvpec',
			'id_user': 'ASH PLANTAIN',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'ASH PLANTAIN',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/1-ASH-PLANTAIN.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'k9v3y2cm': {
			'id': 'k9v3y2cm',
			'id_user': 'BATANA',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'BATANA',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/2-BATANA.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'9el3yh6u': {
			'id': '9el3yh6u',
			'id_user': 'BEET ROOT',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'BEET ROOT',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/3-BEET-ROOT.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'0j1rrysf': {
			'id': '0j1rrysf',
			'id_user': 'BELL PEPPER',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'BELL PEPPER',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/4-BELL-PEPPER.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'ldrj656x': {
			'id': 'ldrj656x',
			'id_user': 'BITTER GOURD',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'BITTER GOURD',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/5-BITTER-GOURD.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'e0e990p9': {
			'id': 'e0e990p9',
			'id_user': 'BRINJAL',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'BRINJAL',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/6-BRINJAL.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'ecbvfmn2': {
			'id': 'ecbvfmn2',
			'id_user': 'BROCCOLI',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'BROCCOLI',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/7-BROCCOLI.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'nqexf7dk': {
			'id': 'nqexf7dk',
			'id_user': 'BREAD FRUIT',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'BREAD FRUIT',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/8-BREAD-FRUIT.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'88vfmbeo': {
			'id': '88vfmbeo',
			'id_user': 'BEANS BUTTER',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'BEANS BUTTER',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/9-BEANS-BUTTER.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'klj3kut3': {
			'id': 'klj3kut3',
			'id_user': 'BEANS GREEN',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'BEANS GREEN',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/10-BEANS-GREEN.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'ic2ijx22': {
			'id': 'ic2ijx22',
			'id_user': 'CABBAGE',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'CABBAGE',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/11-CABBAGE.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'j6pdd4hf': {
			'id': 'j6pdd4hf',
			'id_user': 'CABBAGE RED',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'CABBAGE RED',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/12-CABBAGE-RED.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'q2z363yk': {
			'id': 'q2z363yk',
			'id_user': 'CARROT',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'CARROT',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/14-CARROT.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'onlf2ibd': {
			'id': 'onlf2ibd',
			'id_user': 'CABBAGE CHINESE',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'CABBAGE CHINESE',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/13-CABBAGE-CHINESE.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'a2p3gs87': {
			'id': 'a2p3gs87',
			'id_user': 'CAPSICUM',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'CAPSICUM',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/15-CAPSICUM.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'sy2y6ocw': {
			'id': 'sy2y6ocw',
			'id_user': 'CAULIFLOWER',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'CAULIFLOWER',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/16-CAULIFLOWER.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'y5apniuh': {
			'id': 'y5apniuh',
			'id_user': 'CUCUMBER',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'CUCUMBER',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/18-CUCUMBER.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'2azmoioy': {
			'id': '2azmoioy',
			'id_user': 'CUCUMBER GREEN',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'CUCUMBER GREEN',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/19-CUCUMBER-GREEN.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'q8itjtw0': {
			'id': 'q8itjtw0',
			'id_user': 'CUCUMBER JAPANESE',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'CUCUMBER JAPANESE',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/20-CUCUMBER-JAPANESE.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'fuvj7v7z': {
			'id': 'fuvj7v7z',
			'id_user': 'DAMBALA',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'DAMBALA',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/21-DAMBALA.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'4w31afd5': {
			'id': '4w31afd5',
			'id_user': 'DRUMSTICK',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'DRUMSTICK',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/22-DRUMSTICK.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'tk3h1os6': {
			'id': 'tk3h1os6',
			'id_user': 'EGG PLANT',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'EGG PLANT',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/23-EGG-PLANT.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'b83766xg': {
			'id': 'b83766xg',
			'id_user': 'GREEN CHILLIES',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'GREEN CHILLIES',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/24-GREEN-CHILLIES.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'5jm4d5l9': {
			'id': '5jm4d5l9',
			'id_user': 'ICE BERG',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'ICE BERG',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/25-ICE-BERG.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'8jy4bpdn': {
			'id': '8jy4bpdn',
			'id_user': 'JACK FRUIT',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'JACK FRUIT',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/26-JACK-FRUIT.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'7wumbn5j': {
			'id': '7wumbn5j',
			'id_user': 'KESELMUWA',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'KESELMUWA',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/27-KESELMUWA.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'8pgvr0l3': {
			'id': '8pgvr0l3',
			'id_user': 'KIRI ALA',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'KIRI ALA',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/28-KIRI-ALA.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'gvdwxber': {
			'id': 'gvdwxber',
			'id_user': 'KNOL KHOL',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'KNOL KHOL',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/29-KNOL-KHOL.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'6ksfxu3v': {
			'id': '6ksfxu3v',
			'id_user': 'KOS ATA',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'KOS ATA',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/30-KOS-ATA.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'ozuksgb4': {
			'id': 'ozuksgb4',
			'id_user': 'LADIES FINGER',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'LADIES FINGER',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/31-LADIES-FINGER.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'c1unbone': {
			'id': 'c1unbone',
			'id_user': 'LEEK',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'LEEK',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/32-LEEK.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'5lmn3ge0': {
			'id': '5lmn3ge0',
			'id_user': 'LETTUCE GREEN',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'LETTUCE GREEN',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/33-LETTUCE-GREEN.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'20hyt00y': {
			'id': '20hyt00y',
			'id_user': 'LETTUCE RED',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'LETTUCE RED',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/34-LETTUCE-RED.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'29ik0nnv': {
			'id': '29ik0nnv',
			'id_user': 'LETTUCE BUTTERHEAD',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'LETTUCE BUTTERHEAD',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/35-LETTUCE-BUTTERHEAD.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'xeml0xkq': {
			'id': 'xeml0xkq',
			'id_user': 'LETTUCE COS',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'LETTUCE COS',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/36-LETTUCE-COS.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'u3on82fn': {
			'id': 'u3on82fn',
			'id_user': 'LIME',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'LIME',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/37-LIME.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'jvpnplqz': {
			'id': 'jvpnplqz',
			'id_user': 'LONG BEANS',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'LONG BEANS',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/38-LONG-BEANS.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'l8b8flwf': {
			'id': 'l8b8flwf',
			'id_user': 'LOTUS ROOT',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'LOTUS ROOT',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/39-LOTUS-ROOT.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'uewz0vg4': {
			'id': 'uewz0vg4',
			'id_user': 'LUFFA',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'LUFFA',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/40-LUFFA.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'8dnsintz': {
			'id': '8dnsintz',
			'id_user': 'MANIOC',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'MANIOC',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/41-MANIOC.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'5wqfhrx7': {
			'id': '5wqfhrx7',
			'id_user': 'MINT',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'MINT',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/42-MINT.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'6a3e8lg1': {
			'id': '6a3e8lg1',
			'id_user': 'ONION FLOWER',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'ONION FLOWER',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/43-ONION-FLOWER.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'46gxd34k': {
			'id': '46gxd34k',
			'id_user': 'POTATO',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'POTATO',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/44-POTATO.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'5g6s78zr': {
			'id': '5g6s78zr',
			'id_user': 'POLOS',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'POLOS',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/45-POLOS.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'w8fris6n': {
			'id': 'w8fris6n',
			'id_user': 'PUMPKIN',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'PUMPKIN',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/46-PUMPKIN.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'mzw897o8': {
			'id': 'mzw897o8',
			'id_user': 'RADISH',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'RADISH',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/47-RADISH.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'c69faula': {
			'id': 'c69faula',
			'id_user': 'RADDISH LONG',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'RADDISH LONG',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/48-RADDISH-LONG.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'awwxx1p9': {
			'id': 'awwxx1p9',
			'id_user': 'RADDISH RED',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'RADDISH RED',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/49-RADDISH-RED.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'v7hzfq3i': {
			'id': 'v7hzfq3i',
			'id_user': 'RED UNION',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'RED UNION',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/50-RED-UNION.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'v6ar3tbf': {
			'id': 'v6ar3tbf',
			'id_user': 'SNAKE GUARD',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'SNAKE GUARD',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/51-SNAKE-GUARD.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'aspi0hqv': {
			'id': 'aspi0hqv',
			'id_user': 'SWEET KEKIRI',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'SWEET KEKIRI',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/52-SWEET-KEKIRI.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'kp0ao53u': {
			'id': 'kp0ao53u',
			'id_user': 'SWEET POTATO',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'SWEET POTATO',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/53-SWEET-POTATO.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'yuc1e9vn': {
			'id': 'yuc1e9vn',
			'id_user': 'TALANA BATU',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'TALANA BATU',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/54-TALANA-BATU.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'dsko8fjb': {
			'id': 'dsko8fjb',
			'id_user': 'THUBA KARAWILA',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'THUBA KARAWILA',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/55-THUBA-KARAWILA.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'ac8nqm22': {
			'id': 'ac8nqm22',
			'id_user': 'THIBBATU',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'THIBBATU',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/56-THIBBATU.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'gohmn7ua': {
			'id': 'gohmn7ua',
			'id_user': 'TOMATO',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'TOMATO',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/57-TOMATO.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'dzrrve48': {
			'id': 'dzrrve48',
			'id_user': 'ZUCCHINI GREEN',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'ZUCCHINI GREEN',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/58-ZUCCHINI-GREEN.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'5js4xxzv': {
			'id': '5js4xxzv',
			'id_user': 'ZUCCHINI YELLOW',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'ZUCCHINI YELLOW',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/59-ZUCCHINI-YELLOW.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'5aj4ai4o': {
			'id': '5aj4ai4o',
			'id_user': 'CHAYOTE',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'CHAYOTE',
			'category': 'q8slx9si',
			'description': '',
			'price': 0,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': ['images/17-CHAYOTE.jpg'],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		}
	},

	// Shipping Data
	'shippings': {
		'j48dn4la': {
			'id': 'j48dn4la',
			'name': 'Mail',
			'description': 'The goods will be delivered in 3-5 days.',
			'vat': 0.2,
			'type': 'FIXED',
			'price': 4.1666667,
			'email': 'Shipping by Mail.<br />The goods will be delivered in 3-5 days.'
		},
		'hdj47dut': {
			'id': 'hdj47dut',
			'name': 'Express Delivery',
			'description': 'The goods will be delivered in 1-2 days.',
			'vat': 0.2,
			'type': 'FIXED',
			'price': 8.3333333,
			'email': 'Shipping by Express Delivery.<br />The goods will be delivered in 1-2 days.'
		}
	},

	// Payment Data
	'payments': {
		'8dkejfu5': {
			'id': '8dkejfu5',
			'name': 'Bank Transfer',
			'description': 'Pay later with Bank Transfer.',
			'email': 'The following data is required for payments via Bank Transfers:<br /><br />XXX YYY ZZZ<br /><br />Please note that once the payment is completed it is necessary to send a copy of the receipt along with the Order Number.',
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'pricetype': 'fixed',
			'price': 0
		}
	},

	// User's data form and agreement text
	'form': {
		'agreement': '',
		'acceptAgreement': false,
		'fields': [
			{
				'id': 'Name',
				'uuid': 'Name',
				'name': 'First Name',
				'value': '',
				'type': 'Text',
				'mandatory': true,
				'filter': 'mandatory',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return true;}
			},
			{
				'id': 'LastName',
				'uuid': 'LastName',
				'name': 'Last name',
				'value': '',
				'type': 'Text',
				'mandatory': true,
				'filter': 'mandatory',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return true;}
			},
			{
				'id': 'Address1',
				'uuid': 'Address1',
				'name': 'Address',
				'value': '',
				'type': 'Text',
				'mandatory': true,
				'filter': 'mandatory',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return true;}
			},
			{
				'id': 'ZipPostalCode',
				'uuid': 'ZipPostalCode',
				'name': 'ZIP/Postal Code',
				'value': '',
				'type': 'Text',
				'mandatory': true,
				'filter': 'mandatory',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return true;}
			},
			{
				'id': 'City',
				'uuid': 'City',
				'name': 'City',
				'value': '',
				'type': 'Text',
				'mandatory': true,
				'filter': 'mandatory',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return true;}
			},
			{
				'id': 'StateRegion',
				'uuid': 'StateRegion',
				'name': 'State/Province',
				'value': '',
				'type': 'Text',
				'mandatory': true,
				'filter': 'mandatory',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return $('#' + prefix + 'Country').val() != 'us' && $('#' + prefix + 'Country').val() != 'br' && $('#' + prefix + 'Country').val() != 'US' && $('#' + prefix + 'Country').val() != 'BR';}
			}			,{
				'id': 'StateRegion',
				'uuid': 'StateRegion-us',
				'name': 'State/Province',
				'value': [{"value": "AL","text": "Alabama"},{"value": "AK","text": "Alaska"},{"value": "AZ","text": "Arizona"},{"value": "AR","text": "Arkansas"},{"value": "CA","text": "California"},{"value": "CO","text": "Colorado"},{"value": "CT","text": "Connecticut"},{"value": "DE","text": "Delaware"},{"value": "DC","text": "District of Columbia"},{"value": "FL","text": "Florida"},{"value": "GA","text": "Georgia"},{"value": "HI","text": "Hawaii"},{"value": "ID","text": "Idaho"},{"value": "IL","text": "Illinois"},{"value": "IN","text": "Indiana"},{"value": "IA","text": "Iowa"},{"value": "KS","text": "Kansas"},{"value": "KY","text": "Kentucky"},{"value": "LA","text": "Louisiana"},{"value": "ME","text": "Maine"},{"value": "MD","text": "Maryland"},{"value": "MA","text": "Massachusetts"},{"value": "MI","text": "Michigan"},{"value": "MN","text": "Minnesota"},{"value": "MS","text": "Mississippi"},{"value": "MO","text": "Missouri"},{"value": "MT","text": "Montana"},{"value": "NE","text": "Nebraska"},{"value": "NV","text": "Nevada"},{"value": "NH","text": "New Hampshire"},{"value": "NJ","text": "New Jersey"},{"value": "NM","text": "New Mexico"},{"value": "NY","text": "New York"},{"value": "NC","text": "North Carolina"},{"value": "ND","text": "North Dakota"},{"value": "OH","text": "Ohio"},{"value": "OK","text": "Oklahoma"},{"value": "OR","text": "Oregon"},{"value": "PA","text": "Pennsylvania"},{"value": "RI","text": "Rhode Island"},{"value": "SC","text": "South Carolina"},{"value": "SD","text": "South Dakota"},{"value": "TN","text": "Tennessee"},{"value": "TX","text": "Texas"},{"value": "UT","text": "Utah"},{"value": "VT","text": "Vermont"},{"value": "VA","text": "Virginia"},{"value": "WA","text": "Washington"},{"value": "WV","text": "West Virginia"},{"value": "WI","text": "Wisconsin"},{"value": "WY","text": "Wyoming"}],
				'type': 'DropDownList',
				'mandatory': true,
				'filter': 'mandatory',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return $('#' + prefix + 'Country').val() == 'US' || $('#' + prefix + 'Country').val() == 'us'; }
			},			{
				'id': 'StateRegion',
				'uuid': 'StateRegion-br',
				'name': 'State/Province',
				'value': [{"value": "AC","text": "Acre"},{"value": "AL","text": "Alagoas"},{"value": "AP","text": "Amapá"},{"value": "AM","text": "Amazonas"},{"value": "BA","text": "Bahia"},{"value": "CE","text": "Ceará"},{"value": "DF","text": "Distrito Federal"},{"value": "ES","text": "Espírito Santo"},{"value": "GO","text": "Goiás"},{"value": "MA","text": "Maranhão"},{"value": "MT","text": "Mato Grasso"},{"value": "MS","text": "Mato Grosso do Sul"},{"value": "MG","text": "Minas Gerais"},{"value": "PR","text": "Paraná"},{"value": "PB","text": "Paraíba"},{"value": "PA","text": "Pará"},{"value": "PE","text": "Pernambuco"},{"value": "PI","text": "Piauí"},{"value": "RN","text": "Rio Grande do Norte"},{"value": "RS","text": "Rio Grande do Sul"},{"value": "RJ","text": "Rio de Janeiro"},{"value": "RO","text": "Rondônia"},{"value": "RR","text": "Roraima"},{"value": "SC","text": "Santa Catarina"},{"value": "SE","text": "Sergipe"},{"value": "SP","text": "São Paulo"},{"value": "TO","text": "Tocantins"}],
				'type': 'DropDownList',
				'mandatory': true,
				'filter': 'mandatory',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return $('#' + prefix + 'Country').val() == 'BR' || $('#' + prefix + 'Country').val() == 'br'; }
			},
			{
				'id': 'Phone',
				'uuid': 'Phone',
				'name': 'Telephone',
				'value': '',
				'type': 'Text',
				'mandatory': false,
				'filter': 'valGenTelephone',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return true;}
			},
			{
				'id': 'Email',
				'uuid': 'Email',
				'name': 'Email address',
				'value': '',
				'type': 'Text',
				'mandatory': true,
				'filter': 'mandatory valEmail',
				'shipping': false,
				'custom': false,
				'isVisible': function (prefix) { return true;}
			},
			{
				'id': 'Note',
				'uuid': 'Note',
				'name': 'Note',
				'value': '',
				'type': 'TextArea',
				'mandatory': false,
				'filter': '',
				'shipping': false,
				'custom': true,
				'isVisible': function (prefix) { return true;}
			}
		]
	}
};
x5engine.boot.push('x5engine.cart.manager = new x5engine.cart.ecommerce(x5CartData)');

// End of file x5cart.js